---
- name: Setup apache2 webserver
  hosts: web
  become: true

  tasks:
    - name: Install apache2 and ufw
      ansible.builtin.apt:
        name:
          - apache2
          - ufw
        state: present
        update_cache: true

    - name: Start and enable services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - apache2
        - ufw

    - name: Ensure port 80 is open on the ufw
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp
