---
- name: Set /etc/motd content
  hosts: all:!controller
  become: true
  ## use variables from vars.yaml file
  # vars_files:
  #   - vars.yaml
  ## or in place
  # vars:
  #   motd_content: "custom text\n"

  tasks:
    - name: Set content of /etc/motd
      ansible.builtin.copy:
        dest: /etc/motd
        content: "{{ motd_content }}"
        mode: "0644"

    - name: Get result
      # https://docs.ansible.com/ansible/2.9/modules/command_module.html#command-module
      ansible.builtin.command: "cat /etc/motd"
      register: result
      changed_when: result.rc != 0

    - name: Print result
      ansible.builtin.debug:
        var: result.stdout
