- name: Install postfix and backup its config files
  hosts: ap-worker-node1

  tasks:
    - name: Install postfix package
      ansible.builtin.apt:
        name: postfix
        state: present
        update_cache: true
      become: true

    - name: Find all postfix config files
      # https://docs.ansible.com/ansible/2.9/modules/command_module.html#command-module
      ansible.builtin.command: "find /etc/postfix -type f -name *.cf"
      register: output
      changed_when: output.rc != 0
    # https://docs.ansible.com/ansible/2.9/modules/debug_module.html#debug-module
    - name: Print postfix config files
      ansible.builtin.debug:
        # https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html
        var: output.stdout_lines

    - name: Backup postfix config files
      # https://docs.ansible.com/ansible/2.9/modules/command_module.html#command-module
      ansible.builtin.command:
        cmd: "cp {{ item }} {{ item }}.bak"
        creates: "{{ item }}.bak"
      changed_when: output.rc != 0
      loop: "{{ output.stdout_lines }}"
      become: true
