- name: Service handler
  hosts: web

  tasks:
  - name: Install apache2
    ansible.builtin.apt:
      name: apache2
      state: present
      update_cache: true

  - name: Get apache2 service status
    ansible.builtin.command: "systemctl status apache2"
    changed_when: output.rc != 0
    register: status

  - name: Start apache2 service
    ansible.builtin.command: "systemctl start apache2"
    changed_when: output.rc != 0
    when: status.stdout.find("Active: active (running)") != -1
