---
- name: Secret service
  hosts: nodes
  become: true
  no_log: true
  vars_files:
    - secret_vars.yaml

  tasks:
    - name: Create file with template
      ansible.builtin.template:
        src: mi6.j2
        dest: /etc/MI6
        mode: "0644"
