---
- name: Rebuild webservers
  hosts: web
  sources:
    - name: Start webhook and listen for messages
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Check webservers status and rebuild
      condition: event.payload.message == "webservers down"
      action:
        run_playbook:
          name: playbooks/04-webserver.yaml
