---
- name: Rebuild webservers if webhook receives message
  hosts: web
  sources:
    - name: Start 
      ansible.eda.url_check:
        urls:
          - http://192.168.0.26
          - http://192.168.0.27
        delay: 8
  rules:
    - name: Check webservers status and rebuild
      condition: event.url_check.status == "down"
      action:
        run_playbook:
          name: playbooks/04-webserver.yaml
