---
- name: Rebuild webservers if webhook receives message
  hosts: web
  sources:
    - name: Start webhook and listen for message
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Check webhook message and rebuild
      condition: event.payload.message == "webservers down"
      action:
        run_playbook:
          name: playbooks/04-webserver.yaml
