---
ansible-navigator:
  execution-environment:
    enabled: True
    container-engine: docker
    image: docker.io/library/default-ee
    pull:
      policy: never
    volume-mounts:
      - dest: /runner/ansible-puzzle-labs/.ssh # for ssh key
        src: $HOME/ansible-puzzle-labs/.ssh
      - dest: /home/ansible/ansible-puzzle-labs/ansible/ansible.cfg # for cfg
        src: $HOME/ansible-puzzle-labs/ansible/ansible.cfg

  ansible:
    config:
      path: /home/ansible/ansible-puzzle-labs/ansible/ansible.cfg
    cmdline: "--forks 20"

  color:
    enable: True

  logging:
    level: info
    append: False
    file: logs/log.txt

  playbook-artifact:
    enable: True
    save-as: artifacts/{playbook_name}-artifact-{time_stamp}.json
